name: Publish

on:
  push:
    branches:
    - main
    tags:
    - '!*'

env:
  NODE_VERSION: '16'
  TURBO_TEAM: ${{ secrets.TURBOREPO_REMOTE_CACHING_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBOREPO_REMOTE_CACHING_TOKEN }}

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules/.pnpm
          key: ${{ runner.os }}-node${{ env.NODE_VERSION }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          run_install: |
            - args: [--no-frozen-lockfile, --loglevel=error]

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: pnpm run build

      - name: Create Release or Create Release PR
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          version: pnpm version:prepare
          publish: pnpm version:publish
